# Generated by Django 5.1.1 on 2024-10-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='discount',
        ),
    ]
